#!/bin/bash

export OSOAA_ROOT=/home/${NB_USER}/RadiativeTransferCode-OSOAA
cd /home/${NB_USER}
git clone https://github.com/CNES/RadiativeTransferCode-OSOAA.git
mkdir $OSOAA_ROOT/obj
make -f $OSOAA_ROOT/gen/Makefile_OSOAA.gfortran

git clone https://github.com/fnemina/pyOSOAA.git
cd pyOSOAA
python setup.py install
pip install pyOSOAA