#!/bin/bash

export OSOAA_ROOT=/home/${NB_USER}/RadiativeTransferCode-OSOAA
cd /home/${NB_USER}
git clone https://github.com/CNES/RadiativeTransferCode-OSOAA.git
mkdir $OSOAA_ROOT/obj
make -f $OSOAA_ROOT/gen/Makefile_OSOAA.gfortran

pip install git+https://github.com/fnemina/pyOSOAA
